#+title: vericert
#+man_class_options: :section-id "1"
#+export_file_name: vericert.1

* NAME

vericert - A formally verified high-level synthesis tool.

* SYNOPSYS

*vericert* [ *OPTION* ]... [ *FILE* ]...

* DESCRIPTION

- -drtl :: Print intermediate RTL.

* AUTHOR

Written by Yann Herklotz, Michalis Pardalos, James Pollard, Nadesh Ramanathan and John Wickerson.

* COPYRIGHT

Copyright (C) 2019-2022 Yann Herklotz <yann@yannherklotz.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
